#!/bin/bash
docker buildx create --name mulcpubuilder
docker buildx use mulcpubuilder
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t wesselinktc/homeserver-fe --push .